#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


echo "initrd: enabling USB debugging" >/dev/kmsg || true

path="/sys/class/android_usb/android0"
panicpath="/sys/module/kernel/parameters/panic"

echo 18d1 >$path/idVendor || true
echo D002 >$path/idProduct || true
echo adb >$path/functions || true
echo 1 >$path/enable || true

echo 0 >$panicpath || true

mkdir -p /system/bin
cp /bin/sh /system/bin/

echo "initrd: starting adbd for USB debugging" >/dev/kmsg || true

/sbin/adbd
